### ISSUE TITLE
The InfluxDB pkg version must be pinned to 1.x

### ISSUE THREAD

**Issue by SwannCroiset** [salt-formulas/salt-formula-influxdb#11]
This is to avoid problem like installing the 0.10 while the formula doesn't support it (config parameters not compatible) and also to avoid an automatic major upgrade introducing breaking changes.

**Comment by fpytloun** [comment]
This is more about metadata model and setup of package repositories on given system. Formula should not configure repositories (and pining versions is also configuring repositories) but should just try to use what's available.

**Comment by gthvn1** [comment]
I agree that pinning is not related to the formula but to the user model. So it makes sense to allow the pinning of a specific version from user model. I think about adding something like:
```
  pkg.installed:
  - names: {{ server.pkgs }}
  {%- if server.version is defined %}
  - version: {{ server.version }}
  {%- endif %}
```
but I guess that *names* and *version* are not really compatible :-(... What is the better way to specify a version in the model?

**Comment by SwannCroiset** [comment]
do what you want guys
